### ISSUE TITLE
How to solve the problem ,when running ‘ python setup.py install --home="."   ’

### ISSUE THREAD

**Issue by chiyandetaotie** [aboulch/snapnet#19]
Hello Prof：
Something wrong with  running ‘python setup.py install --home="."   
It shows:
```
(snapnet) yl@yl:~/PycharmProjects/snapnet-master1/pointcloud_tools$ python setup.py install --home="."

running install
running build
running build_ext
skipping 'Semantic3D.cpp' Cython extension (up-to-date)
building 'PcTools' extension
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ithird_party_includes/ -I/usr/local/include/pcl-1.8 -I/usr/local/include/vtk-7.1 -I/home/yl/anaconda3/envs/snapnet/include/python3.6m -c Semantic3D.cpp -o build/temp.linux-x86_64-3.6/Semantic3D.o -fopenmp -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
Semantic3D.cpp:449:31: fatal error: numpy/arrayobject.h: No such file or directory
 #include "numpy/arrayobject.h"
                               ^
compilation terminated.
error: command 'gcc' failed with exit status 1
```

How can I to solve "fatal error: numpy/arrayobject.h : No such file or directory"
I have modified  the srtup.py  ,as follows:
```
from distutils.core import setup
from distutils.extension import Extension
from Cython.Distutils import build_ext


pcl_include_dir = "/usr/local/include/pcl-1.8"
pcl_lib_dir = "/usr/local/lib"
vtk_include_dir = "/usr/local/include/vtk-7.1"
#vtk_include_dir = "/usr/include/vtk-6.2"

# depending on the distribution, change the directory according to the installed version
# example for stock ubuntu 16.04:
# vtk_include_dir = "/usr/include/vtk-5.10"

ext_modules = [Extension(
       "PcTools",
       sources=["Semantic3D.pyx", "Sem3D.cxx","pointCloud.cxx", "pointCloudLabels.cxx"],  # source file(s)
       include_dirs=["third_party_includes/",pcl_include_dir, vtk_include_dir],
       language="c++",             # generate C++ code
       library_dirs=[pcl_lib_dir],
       libraries=["pcl_common","pcl_kdtree","pcl_features","pcl_surface","pcl_io"],
       extra_compile_args = ["-fopenmp", "-std=c++11"]
  )]

setup(
    name = "PointCloud tools",
    ext_modules = ext_modules,
    cmdclass = {'build_ext': build_ext},
)
```

**Add this is my anaconda environment**

```
(snapnet) yl@yl:~/PycharmProjects/snapnet-master1/pointcloud_tools$ conda list
# packages in environment at /home/yl/anaconda3/envs/snapnet:
#
# Name                    Version                   Build  Channel
_license                  1.1                      py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
absl-py                   0.7.1                    pypi_0    pypi
alabaster                 0.7.10                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
anaconda                  4.4.0               np112py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
anaconda-client           1.6.3                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
anaconda-navigator        1.6.2                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
anaconda-project          0.6.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
asn1crypto                0.22.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
astor                     0.7.1                    pypi_0    pypi
astroid                   1.4.9                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
astropy                   1.3.2               np112py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
babel                     2.4.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
backports                 1.0                      py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
beautifulsoup4            4.6.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
bitarray                  0.8.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
blaze                     0.10.1                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
bleach                    1.5.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
bokeh                     0.12.5                   py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
boto                      2.46.1                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
bottleneck                1.2.1               np112py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
cairo                     1.14.8                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
cffi                      1.10.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
chardet                   3.0.3                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
click                     6.7                      py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
cloudpickle               0.2.2                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
clyent                    1.2.2                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
colorama                  0.3.9                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
contextlib2               0.5.5                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
cryptography              1.8.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
curl                      7.52.1                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
cycler                    0.10.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
cython                    0.25.2                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
cytoolz                   0.8.2                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
dask                      0.14.3                   py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
datashape                 0.5.4                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
dbus                      1.10.10                       0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
decorator                 4.0.11                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
distributed               1.16.3                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
docutils                  0.13.1                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
entrypoints               0.2.2                    py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
et_xmlfile                1.0.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
expat                     2.1.0                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
fastcache                 1.0.2                    py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
flask                     0.12.2                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
flask-cors                3.0.2                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
fontconfig                2.12.1                        3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
freetype                  2.5.5                         2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
gast                      0.2.2                    pypi_0    pypi
get_terminal_size         1.0.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
gevent                    1.2.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
glib                      2.50.2                        1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
greenlet                  0.4.12                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
grpcio                    1.19.0                   pypi_0    pypi
gst-plugins-base          1.8.0                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
gstreamer                 1.8.0                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
h5py                      2.7.0               np112py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
harfbuzz                  0.9.39                        2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
hdf5                      1.8.17                        1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
heapdict                  1.0.0                    py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
html5lib                  0.9999999                pypi_0    pypi
icu                       54.1                          0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
idna                      2.5                      py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
imagesize                 0.7.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
ipykernel                 4.6.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
ipython                   5.3.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
ipython_genutils          0.2.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
ipywidgets                6.0.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
isort                     4.2.5                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
itsdangerous              0.24                     py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
jbig                      2.1                           0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
jdcal                     1.3                      py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
jedi                      0.10.2                   py36_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
jinja2                    2.9.6                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
jpeg                      9b                            0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
jsonschema                2.6.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
jupyter                   1.0.0                    py36_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
jupyter_client            5.0.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
jupyter_console           5.1.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
jupyter_core              4.3.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
lazy-object-proxy         1.2.2                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libffi                    3.2.1                         1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libgcc                    4.8.5                         2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libgfortran               3.0.0                         1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libiconv                  1.14                          0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libpng                    1.6.27                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libsodium                 1.0.10                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libtiff                   4.0.6                         3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libtool                   2.4.2                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libxcb                    1.12                          1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libxml2                   2.9.4                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libxslt                   1.1.29                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
llvmlite                  0.18.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
locket                    0.2.0                    py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
lxml                      3.7.3                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
markdown                  3.1                      pypi_0    pypi
markupsafe                0.23                     py36_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
matplotlib                2.0.2               np112py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
mistune                   0.7.4                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
mkl                       2017.0.1                      0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
mkl-service               1.1.2                    py36_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
mpmath                    0.19                     py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
msgpack-python            0.4.8                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
multipledispatch          0.4.9                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
navigator-updater         0.1.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
nbconvert                 5.1.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
nbformat                  4.3.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
networkx                  1.11                     py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
nltk                      3.2.3                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
nose                      1.3.7                    py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
notebook                  5.0.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
numba                     0.33.0              np112py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
numexpr                   2.6.2               np112py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
numpy                     1.16.2                   pypi_0    pypi
numpydoc                  0.6.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
odo                       0.5.0                    py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
olefile                   0.44                     py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
openpyxl                  2.4.7                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
openssl                   1.0.2l                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
packaging                 16.8                     py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pandas                    0.20.1              np112py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pandocfilters             1.4.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pango                     1.40.3                        1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
partd                     0.3.8                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
path.py                   10.3.1                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pathlib2                  2.2.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
patsy                     0.4.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pcre                      8.39                          1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pep8                      1.7.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pexpect                   4.2.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pickleshare               0.7.4                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pillow                    4.1.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pip                       9.0.1                    py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pixman                    0.34.0                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
ply                       3.10                     py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
prompt_toolkit            1.0.14                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
protobuf                  3.7.1                    pypi_0    pypi
psutil                    5.2.2                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
ptyprocess                0.5.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
py                        1.4.33                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pycosat                   0.6.2                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pycparser                 2.17                     py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pycrypto                  2.6.1                    py36_6    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pycurl                    7.43.0                   py36_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pyflakes                  1.5.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pygments                  2.2.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pylint                    1.6.4                    py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pyodbc                    4.0.16                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pyopenssl                 17.0.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pyparsing                 2.1.4                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pyqt                      5.6.0                    py36_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pytables                  3.3.0               np112py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pytest                    3.0.7                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
python                    3.6.1                         2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
python-dateutil           2.6.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pytz                      2017.2                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pywavelets                0.5.2               np112py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pyyaml                    3.12                     py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pyzmq                     16.0.2                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
qt                        5.6.2                         4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
qtawesome                 0.4.4                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
qtconsole                 4.3.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
qtpy                      1.2.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
readline                  6.2                           2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
requests                  2.14.2                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
rope                      0.9.4                    py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
ruamel_yaml               0.11.14                  py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
scikit-image              0.13.0              np112py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
scikit-learn              0.18.1              np112py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
scipy                     0.19.0              np112py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
seaborn                   0.7.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
setuptools                27.2.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
simplegeneric             0.8.1                    py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
singledispatch            3.4.0.3                  py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
sip                       4.18                     py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
six                       1.10.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
snowballstemmer           1.2.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
sortedcollections         0.5.3                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
sortedcontainers          1.5.7                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
sphinx                    1.5.6                    pypi_0    pypi
spyder                    3.1.4                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
sqlalchemy                1.1.9                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
sqlite                    3.13.0                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
statsmodels               0.8.0               np112py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
sympy                     1.0                      py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
tblib                     1.3.2                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
tensorboard               1.7.0                    pypi_0    pypi
tensorflow                1.7.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.6                      py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
testpath                  0.3                      py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
tk                        8.5.18                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
toolz                     0.8.2                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
tornado                   4.5.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
tqdm                      4.15.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
traitlets                 4.3.2                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
unicodecsv                0.14.1                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
unixodbc                  2.3.4                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
wcwidth                   0.1.7                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
werkzeug                  0.12.2                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
wheel                     0.29.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
widgetsnbextension        2.0.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
wrapt                     1.10.10                  py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
xlrd                      1.0.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
xlsxwriter                0.9.6                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
xlwt                      1.2.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
xz                        5.2.2                         1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
yaml                      0.1.6                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
zeromq                    4.1.5                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
zict                      0.1.2                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
zlib                      1.2.8                         3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
```

**And I find the file '' arrayobject.h '' in the path '' /home/yl/anaconda3/envs/snapnet/lib/python3.6/site-packages/numpy/core/include/numpy ''**

**Comment by chiyandetaotie** [comment]
Hello Prof：
I solve the problem by adding the path of  the file '' arrayobject.h '' in the setup.py,like this:
```
from distutils.core import setup
from distutils.extension import Extension
from Cython.Distutils import build_ext


pcl_include_dir = "/usr/local/include/pcl-1.8"
pcl_lib_dir = "/usr/local/lib"
vtk_include_dir = "/usr/local/include/vtk-7.1"
arrar_dir = "/home/yl/anaconda3/envs/snapnet/lib/python3.6/site-packages/numpy/core/include/"
# depending on the distribution, change the directory according to the installed version
# example for stock ubuntu 16.04:
# vtk_include_dir = "/usr/include/vtk-5.10"

ext_modules = [Extension(
       "PcTools",
       sources=["Semantic3D.pyx", "Sem3D.cxx","pointCloud.cxx", "pointCloudLabels.cxx"],  # source file(s)
       include_dirs=["third_party_includes/",pcl_include_dir, vtk_include_dir, arrar_dir],
       language="c++",             # generate C++ code
       library_dirs=[pcl_lib_dir],
       libraries=["pcl_common","pcl_kdtree","pcl_features","pcl_surface","pcl_io"],
       extra_compile_args = ["-fopenmp", "-std=c++11"]
  )]

setup(
    name = "PointCloud tools",
    ext_modules = ext_modules,
    cmdclass = {'build_ext': build_ext},
)
```
**It could generate the pictures ,but when training the model by " python3 sem3d_train_tf.py --config config.json ",it shows the problem :**

```
 2 2 2 2 3 3 2 2 3 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 2 2 2 3 2 3 3 3 3 2 2 2 2 0 3 3 3 3 2 2 2 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 6 6 6 6 6 6 6 6 6 6 6 6 6 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 2 
2 2 2 2 2 2 2 2 3 3 3 3 2 2 2 2 2 2 3 3 2 2 2 2 2 2 3 3 3 3 2 3 3 3 3 3 3 3 3 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 
3 3 3 3 3 3 3 3 3 3 3 3 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 
0 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 6 6 6 6 6 6 6 6 6 6 6 6 6 6 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 2 0 2 2 2 2 2 2 2 2 2 2 3 3 2 2 2 3 3 3
 3 3 3 2 2 2 2 2 2 2 2 2 3 3 3 3 3 2 2 2 3 3 3 3 2 2 2 2 2 3 3 3 3 3 2 3 3 2 3 3 3 3 3 3 2 2 2 0 0 3 3 3 3 2 2 
3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 0 0 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 6 6 6 6 6 6 6 6 6 6 6 6 6 6 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 2 2 2 2 3 3 2 2 2 2 2 2 3 3 3 2 
2 3 3 3 3 3 3 3 2 2 2 2 2 2 2 2 3 3 3 3 3 3 2 3 3 3 3 3 2 2 2 2 2 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 2 2 2 0 0 3 3
 3 3 2 3 3 2 3 3 3 3 3 3 3 3 3 3 3 3 3 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 0 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 6 6 6 6 6 6 6 6 6 6 1 6 6 6 6 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1
	 [[Node: sparse_softmax_cross_entropy_loss/xentropy/xentropy =
 SparseSoftmaxCrossEntropyWithLogits[T=DT_FLOAT, Tlabels=DT_INT32, 
_device="/job:localhost/replica:0/task:0/device:CPU:0"](Reshape_1, 
sparse_softmax_cross_entropy_loss/Reshape)]]

Exception ignored in: <bound method tqdm.__del__ of   0%| 
                                                       | 0/1 [00:37<?, ?it/s]>
Traceback (most recent call last):
  File "/home/yl/anaconda3/envs/snapnet/lib/python3.6/site-packages/tqdm/_tqdm.py", line 931, in __del__
    self.close()
  File "/home/yl/anaconda3/envs/snapnet/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1133, in close
    self._decr_instances(self)
  File "/home/yl/anaconda3/envs/snapnet/lib/python3.6/site-packages/tqdm/_tqdm.py", line 496, in _decr_instances
    cls.monitor.exit()
  File "/home/yl/anaconda3/envs/snapnet/lib/python3.6/site-packages/tqdm/_monitor.py", line 52, in exit
    self.join()
  File "/home/yl/anaconda3/envs/snapnet/lib/python3.6/threading.py", line 1053, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
```
 **What is wrong? How can I solve it ? Looking forword to your reply.**
