### ISSUE TITLE
Got issue from training

### ISSUE THREAD

**Issue by syncle** [aboulch/snapnet#7]
Hi @aboulch 

Thanks for releasing this code! I have tried to re-train the network, but got following error.
```
Traceback (most recent call last):
  File "sem3d_train_tf.py", line 55, in <module>
    variable_scope="rgb")
  File "/semanticsegmentation/snapnet/python/tensorflow_trainer.py", line 37, in train
    deconv_net, net = self.model_function(images, label_nbr)
  File "/semanticsegmentation/snapnet/python/models/tensorflow_unet.py", line 42, in model
    net = VGG16_net({'data': images})
  File "kaffe/tensorflow/network.py", line 47, in __init__
    self.setup()
  File "/semanticsegmentation/snapnet/python/models/VGG_ILSVRC_16_layers.py", line 41, in setup
    .max_pool(2, 2, 2, 2, name='pool1', with_argmax=True) # use argmax
  File "kaffe/tensorflow/network.py", line 21, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
TypeError: max_pool() got an unexpected keyword argument 'with_argmax'
```

This error is due to
https://github.com/aboulch/snapnet/blob/aa0fe5a3e00c5996a4cfaa15b98b9ec8e584aade/python/models/VGG_ILSVRC_16_layers.py#L8

I am using ``network.py`` from [kaffe repository](https://github.com/ethereon/caffe-tensorflow/blob/master/kaffe/tensorflow/network.py). Obviously, ``max_pool`` attribute does not have ``with_argmax``. For instance,

```
    @layer
    def max_pool(self, input, k_h, k_w, s_h, s_w, name, padding=DEFAULT_PADDING):
        self.validate_padding(padding)
        return tf.nn.max_pool(input,
                              ksize=[1, k_h, k_w, 1],
                              strides=[1, s_h, s_w, 1],
                              padding=padding,
                              name=name)
```

Have you used custom ``network.py`` file? It would be good if your kaffe is included/shared in this repository too. Thanks.

**Comment by syncle** [comment]
If I am not wrong, this modification fixes the above issue

```
    @layer
    def max_pool(self, input, k_h, k_w, s_h, s_w, name, padding=DEFAULT_PADDING, with_argmax=False):
        self.validate_padding(padding)
        if with_argmax:
            return tf.nn.max_pool_with_argmax(input,
                                  ksize=[1, k_h, k_w, 1],
                                  strides=[1, s_h, s_w, 1],
                                  padding=padding,
                                  name=name)
        else:
            return tf.nn.max_pool(input,
                                  ksize=[1, k_h, k_w, 1],
                                  strides=[1, s_h, s_w, 1],
                                  padding=padding,
                                  name=name)
```
but I got another error.

```
Traceback (most recent call last):
  File "sem3d_train_tf.py", line 12, in <module>
    import python.models.tensorflow_unet as model
  File "/semanticsegmentation/snapnet/python/models/tensorflow_unet.py", line 11, in <module>
    @ops.RegisterGradient("MaxPoolWithArgmax")
  File "/anaconda3/envs/py36snapnet/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2085, in __call__
    _gradient_registry.register(f, self._op_type)
  File "/anaconda3/envs/py36snapnet/lib/python3.6/site-packages/tensorflow/python/framework/registry.py", line 62, in register
    (self._name, name, function_name, filename, line_number))
KeyError: "Registering two gradient with name 'MaxPoolWithArgmax' !(Previous registration was in _find_and_load_unlocked <frozen importlib._bootstrap>:955)"
```
I am using TensorFlow 1.4.1 + Ubuntu 16.04 + Anaconda Python 3.6. Can you help me to resolve this issue? Thanks!

**Comment by aboulch** [comment]
Hello,
Sorry for late response, I will look into that as soon as I can (I hope before the end the week).
This is due to double Registration of modules => it seems there is another module somewhere with the same name.

**Comment by aboulch** [comment]
Hello,
I made changes in the repo, removed the MaxPoolWithArgmax that was left from a previous test with SegNet. I also remove dependencies to Kaffe, the weights to be loaded are still the same but they are now loaded directly in the UNet file.

**Comment by syncle** [comment]
Thanks a lot @aboulch! That is definitely helpful. I will check out the new code.

**Comment by syncle** [comment]
Updates: I was able to run ``sem3d_train_tf.py`` without ``MaxPoolWithArgmax`` issues. I appreciate for the support. 

However I got this run-time error message

```
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[24,192,224,224]
	 [[Node: gradients/rgb/BatchNorm_3/FusedBatchNorm_grad/FusedBatchNormGrad = FusedBatchNormGrad[T=DT_FLOAT, data_format="NHWC", epsilon=0.001, is_training=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/rgb/Conv2d_transpose_10/conv2d_transpose_grad/tuple/control_dependency_1, rgb/concat_3, rgb/BatchNorm_3/Const, rgb/BatchNorm_3/FusedBatchNorm:3, rgb/BatchNorm_3/FusedBatchNorm:4)]]
```

I am using Titan X (Pascal) with 10GB free memory. I wonder my GPU need larger memory (or something is wrong). Can you tell your training environment?

**Comment by syncle** [comment]
I was able to resolve this issue with TITAN X (Pascal) having 12GB free memory.

**Comment by aboulch** [comment]
Hello,
If the problem appears again: you can reduce the batchsize in the config file.
